// apps/sandbox-astro5/src/components/solid/Counter/Counter.tsx
import { createSignal } from 'solid-js';

const Counter = () => {
  const [count, setCount] = createSignal(1);

  return (
    <div data-testid="solid-counter">
      <span>Solid counter: {count()}</span>
      {' '}
      <button
        onClick={() => {
          setCount((prev) => prev + 1);
        }}
      >
        +1
      </button>
    </div>
  );
};

export default Counter;

// packages/components/src/Counter/react/Counter.jsx
import React, { useState } from 'react';

function Counter() {
  const [count, setCount] = useState(1);

  return (
    <div data-testid="react-counter">
      <span>React counter: {count}</span>
      <button onClick={() => setCount(count + 1)}>+1</button>
    </div>
  );
}

export default Counter;
