// packages/components/src/Counter/react/Counter.jsx
import React, { useState } from 'react';

function Counter() {
  const [count, setCount] = useState(1);

  return (
    <div data-testid="react-counter">
      <span>React counter: {count}</span>
      <button onClick={() => setCount(count + 1)}>+1</button>
    </div>
  );
}

export default Counter;

// packages/components/src/Counter/vue/Counter.vue
<template>
  <div data-testid="vue-counter">
    <span>Vue counter: {{ count }}</span>
    {{ ' ' }}
    <button @click="increment">
      +1
    </button>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'CounterComponent',
  setup() {
    const count = ref(1);

    const increment = () => {
      count.value += 1;
    };

    return {
      count,
      increment
    };
  }
};
</script>
