// apps/sandbox-astro5/src/components/solid/Counter/Counter.tsx
import { createSignal } from 'solid-js';

const Counter = () => {
  const [count, setCount] = createSignal(1);

  return (
    <div data-testid="solid-counter">
      <span>Solid counter: {count()}</span>
      {' '}
      <button
        onClick={() => {
          setCount((prev) => prev + 1);
        }}
      >
        +1
      </button>
    </div>
  );
};

export default Counter;

// apps/sandbox-astro5/src/components/preact/Counter/Counter.jsx
import { useState } from 'preact/hooks';

export default function Counter() {
  const [count, setCount] = useState(1);

  return (
    <div data-testid="preact-counter">
      <span>Preact counter: {count}</span>
      {' '}
      <button onClick={() => setCount(count + 1)}>+1</button>
    </div>
  );
}
